// T6 Behavior Descriptions — 132 items for the BIM Masterwheel

export const behaviorDescriptions = [
"Raised tone, sharp posture",
"Direct challenge, strong body language",
"Threatening stance, pointed words",
"Physical threat or verbal explosion",
"Small act of passive resistance",
"Snappy comeback, cutting remark",
"Punitive action or harsh payback",
"Full revenge, vengeful action",
"Positions self slightly above others",
"Takes control of decisions or space",
"Dismisses others’ input; sets unilateral direction",
"Enforces power harshly, silences dissent",
"Offers a soft explanation or redirect",
"Pushes back with detailed rationale",
"Blocks, argues, reframes to avoid discomfort",
"Redirects blame, flips guilt, attacks vulnerability",
"Uses indirect tone, sarcasm, or minor pushback",
"Plans or delivers a proportionate hitback",
"Delivers verbal or emotional strike to ‘even score’",
"Explodes with targeted attack, punishment-focused",
"Sudden shift in topic or attention, mild deflection",
"Clearly dodges, repositions self or convo with intent",
"Actively escapes emotional contact or mental confrontation",
"Urgent, near-reflexive mental or physical exit",
"Stirring energy, mildly disruptive or disorganised",
"Emotional content spills out in tangled ways",
"Energy spikes and disorganises, volatile actions or speech",
"Breaks reality coherence — intense, unfiltered chaos state",
"Light sarcasm, subtle pushback cloaked as wit or banter",
"Deflective but more pointed — blends anger with defence",
"Full deflection with force, mixes hurt and aggression",
"Explosive verbal offence from deep internal unrest",
"Pulling back slightly, needing a little space or quiet",
"Disengages emotionally to avoid escalation",
"Withdraws fully from the person or situation",
"Disappears into silence or isolation to protect self",
"Skips or redirects mildly uncomfortable interactions",
"Purposefully avoids certain topics, people, or settings",
"Regularly avoids responsibilities, conflicts, or emotional engagement",
"Creates distance through distraction, denial, or full disengagement",
"Lightly avoids direct answers or commitments",
"Skilfully dodges confrontations or vulnerability",
"Uses redirection or ambiguity to deflect perceived threat",
"Full deployment of charm, confusion, or chaos to prevent real contact",
"Steps back with uncertainty, unsure whether to engage or escape",
"Begins avoiding people or topics that increase internal tension",
"Strong pull away from interaction or self-expression",
"Overwhelmed, retreating into silence, tears, or freeze states",
"Keeps an exit open without leaving, emotionally or physically",
"Begins to fabricate or reach for reasons to leave or not engage",
"Struggles to remain, showing visible discomfort and avoidance",
"Nods or agrees while mentally disconnecting to avoid further strain",
"Stalls before replying, slow or paused response",
"Numbly avoids tasks or conversation, spacing out or ghosting",
"Words and thoughts collapse, flooded by internal overwhelm",
"Cannot engage at all — avoids entirely or becomes unreachable",
"Pulls inward, avoids eye contact, subtle freeze or silence",
"Goes quiet, shuts down emotionally, minimal interaction",
"Can’t function — lies down, curls up, words absent",
"Fully unresponsive — catatonia, no external engagement",
"Mind wanders off mid-conversation, feels floaty or “not here”",
"Time skips, blank moments, can’t recall parts of conversation",
"Voice flattens, may refer to self in third person or feel out-of-body",
"Full alter state, high dissociation, reality fragmentation",
"Body freezes slightly, small muscle tension, slowed breathing",
"Locked limbs, can’t act or respond, feels pinned or heavy",
"Full freeze with internal panic, heartbeat racing, but body still",
"Total collapse into freeze, disconnection from time and control",
"Appears agreeable but vacant, subtle detachment masked as cooperation",
"Repetitive compliance goes along without internal alignment",
"Fully dissociated while following commands, blank affect, functional autopilot",
"Performs under extreme dissociation, personal will absent",
"Complies gently to avoid conflict, subtly evading deeper connection",
"Offers superficial agreement to prevent escalation or discomfort",
"Leans into passivity as a way to soothe others and disarm tension",
"Fully melts into the background to avoid being targeted or blamed",
"Becomes overly attuned to others’ feelings to stay safe or accepted",
"Seeks emotional enmeshment as protection from abandonment or disapproval",
"Fears emotional distance as threat, floods others with need for reconnection",
"Fully loses personal boundaries, dissolves into the identity of the other",
"Nods along with minimal input to stay aligned with external expectations",
"Follows rules or suggestions despite internal objection",
"Suppresses needs, voice, or values to preserve external harmony",
"Forfeits autonomy entirely to avoid disruption or rejection",
"Adjusts responses and behaviour to keep others happy, even at small cost to self",
"Monitors reactions and edits personality to avoid conflict or disappointment",
"Sacrifices needs, opinions, or desires to gain external validation",
"Internal compass dissolves; becomes entirely other-oriented for acceptance",
"Downplays personal needs and yields slightly to ease social tension",
"Preemptively smooths over tension, avoids confrontation by appeasing",
"Tries to prevent escalation through excessive compliance or deference",
"Fully suppresses self in hopes of preserving peace in unsafe dynamics",
"Offers slightly more support than needed, even when unasked",
"Struggles to let others manage discomfort, tries to fix or soothe everything",
"Ignores personal limits to provide for others, sacrifices time and self-care",
"Entire identity centres around being needed, caretaking becomes self-worth",
"Downplays needs or preferences to maintain harmony",
"Regularly gives up personal desires to avoid conflict or loss",
"Redefines self around another’s needs; ignores core values or dreams",
"Fully abandons selfhood, values, boundaries to maintain proximity",
"Frequently initiates casual connection and light conversation",
"Seeks frequent social affirmation to feel okay or reassured",
"Becomes emotionally dependent on constant interaction for self-stability",
"Uses others’ presence to numb, distract, or validate an unstable inner world",
"Offers support through warm presence and small, thoughtful actions",
"Attunes to others’ needs and offers emotional or physical support",
"Takes on emotional labour to care for others through crisis or distress",
"Smothers others with care, struggling to allow autonomy or detachment",
"Engages with lighthearted openness and gestures of connection",
"Builds consistency and trust through shared experiences and follow-through",
"Integrates others into daily rhythm and creates emotional interdependence",
"Pushes for closeness at all costs, fearing loss of connection or being forgotten",
"Offers gentle affirmation and presence without intrusion",
"Provides clear, grounded aid where needed without taking over",
"Emotionally steadies another during challenge, offering deep listening and grounding",
"Attempts to manage the other’s emotional state, often overriding their process",
"Creates a soft protective buffer around the vulnerable without restricting them",
"Sets clear lines to keep others safe while remaining emotionally connected",
"Guards emotionally while offering reassurance, often becoming directive",
"Overly controls or limits to protect, potentially limiting growth or freedom",
"Gently asserts limits while offering care and clarity",
"Delivers firm boundaries while remaining emotionally regulated",
"Establishes protective rules, may limit contact or behaviour to preserve wellness",
"Implements hard limits, may sever ties or take decisive action for protection",
"Offers proactive help while respecting autonomy",
"Steps in with clarity, provides direction when needed",
"Directs others with a balance of firmness and care",
"Takes command in crisis to prevent harm or restore order",
"Offers specific advice or assistance while honouring autonomy",
"Gives clear input or steps to assist, with concern and respect",
"Asserts what needs to happen for the other’s well-being, prioritising their needs",
"Takes charge of care actions when someone is unable or unwilling to act for themselves",
];
