// emotion.js — Emotion/Feeling data for T6 view mode

export const emotion = [
  "Irritation",
"Anger rising",
"Rage",
"Fury",
"Resentment",
"Spite / Frustration",
"Rage + Justification",
"Consuming Fury",
"Composed Authority",
"Determined",
"Frustration + Control",
"Dominance / Entitlement",
"Unease / Vulnerability",
"Frustration / Guarded",
"Annoyed / Misread",
"Rage / Shame Aversion",
"Irritation / Spite",
"Bitterness / Justice Drive",
"Anger / Moral Certainty",
"Rage / Vengefulness",
"Nervousness, Distracted",
"Wariness, Agitation",
"Internal pressure, Shutdown building",
"Alarm, Overwhelm",
"Restless, Unsettled",
"Confused, Frustrated",
"Rage, Helplessness",
"Identity panic, Dissociation",
"Irritated, Guarded",
"Resentful, Defensive",
"Betrayed, Cornered",
"Fury, Shame",
"Drained, Cautious",
"Defensive, Detached",
"Overwhelmed, Angry",
"Shut down, Disconnected",
"Uneasy, Hesitant",
"Anxious, Defensive",
"Frustrated, Drained",
"Trapped, Overwhelmed",
"Cautious, Wary",
"Anxious, Strategizing",
"Defensive, Calculating",
"Masked, Unreachable",
"Uneasy, Overthinking",
"Nervous, Preoccupied",
"Alarmed, Shutting Down",
"Flooded, Dissociative",
"On edge, Distracted",
"Pressured, Preoccupied",
"Conflicted, Unsettled",
"Resigned, Disconnected",
"Foggy, Disoriented",
"Numb, Tense",
"Frazzled, Pressured",
"Overstimulated, Paralyzed",
"Quiet, Hesitant",
"Numb, Internalized",
"Hopeless, Paralyzed",
"Blank, Vacant",
"Fuzzy, Aloof",
"Blank, Surreal",
"Disembodied, Unreal",
"Fragmented, Absent",
"Startled, Conflicted",
"Paralyzed, Overwhelmed",
"Panic, Suppressed",
"Void, Terror",
"Numb, Wary",
"Disconnected, Drained",
"Defeated, Empty",
"Vanished, Subjugated",
"Mild Anxiety, Unsettled",
"Tense, Uncomfortable",
"Uneasy, Dissolving",
"Powerless, Dissolved",
"Nervous, Eager-to-Please",
"Uneasy, Dependent",
"Panic, Fragile",
"Terror, Emptiness",
"Mild tension, Hesitation",
"Low-level frustration",
"Frustration, Powerlessness",
"Resignation, Emptiness",
"Warm anxiety, Discomfort",
"Anxious care, Self-doubt",
"Insecurity, Over-concern",
"Panic, Abandonment Fear",
"Mild fear, Unease",
"Anxious, Placating",
"Submission, Fear",
"Panic, Dissolution",
"Care, Preoccupation",
"Anxiety, Over-empathy",
"Guilt, Suppressed need",
"Panic, Loss of self",
"Care, Mild Resignation",
"Longing, Duty",
"Powerlessness, Grief",
"Despair, Dissociation",
"Warmth, Mild Restlessness",
"Insecurity, Eagerness",
"Anxiety, Fragmentation",
"Panic, Dissociation",
"Care, Calm",
"Concern, Attunement",
"Compassion, Steadiness",
"Anxiety, Enmeshment",
"Affection, Curiosity",
"Stability, Fondness",
"Deep Affection",
"Anxiety, Dependency",
"Care, Openness",
"Reliability, Calm",
"Empathy, Commitment",
"Over-responsibility",
"Concern, Soft Strength",
"Clarity, Responsibility",
"Vigilance, Affection",
"Overattachment, Fear",
"Groundedness, Resolve",
"Self-respect, Clarity",
"Frustration, Self-worth",
"Exhaustion, Protection",
"Readiness, Care",
"Confidence, Encouragement",
"Focus, Leadership",
"Urgency, Protection",
"Consideration, Care",
"Clarity, Assurance",
"Steady Resolve",
"Urgency, Fierce Care"
];
