// quotes.js — T6 Dataset: Expression Quotes

export const quotes = [
"Don’t start with me.",
"I said enough.",
"Back off now!",
"Try me.",
"We’ll see about that.",
"You’ll regret that.",
"You asked for this.",
"Now you’ll feel it.",
"Let me take the lead.",
"Here’s how it’s going to work.",
"I’ll do it my way.",
"I’m in charge. End of story.",
"That’s not quite what I meant.",
"You’re misunderstanding me.",
"That’s not fair to say.",
"You’re the one who did that, not me!",
"Funny how that keeps happening…",
"Let’s see how you like it.",
"You asked for this.",
"You’ll regret that for the rest of your life.",
"Oh hey, did you see that?",
"Let's not go there, alright?",
"Not now. I don’t have the bandwidth.",
"I can’t — I’m out!",
"Wait—what were we even talking about?",
"You just don’t get it! None of this makes sense!",
"Screw it, I’m done talking!",
"I don’t know who I am or what this is!",
"Oh, sure, like I’d ever do that...",
"You’re one to talk...",
"You really think this is my fault?",
"You’re the real problem here!",
"I just need a minute…",
"I’m done with this conversation.",
"Leave me alone.",
"(No response. Silence.)",
"Let’s talk about it later.",
"I don’t want to get into that.",
"I’ll deal with it when I have to.",
"I’m out. Don’t ask me again.",
"Hmm, we’ll see...",
"Let’s not go there right now.",
"Why are you asking me that?",
"Don’t worry about me—what about you?",
"I just need a sec to think.",
"Can we talk about this later?",
"I can’t do this right now.",
"Everything’s too much…",
"I might step out for a moment...",
"I’ve got something else I should do…",
"This doesn’t feel right…",
"Yeah, okay…",
"Umm… give me a second…",
"Sorry, I just blanked out…",
"I can’t think right now…",
"[No response]",
"I just… don’t know right now.",
"I don’t really feel anything.",
"[Head shake]",
"[No response at all]",
"Sorry, what were you saying?",
"It’s like I just… wasn’t here.",
"It’s like I’m watching it happen.",
"[Incongruent tone or silence]",
"I couldn’t move for a second.",
"It’s like I got stuck.",
"I was screaming inside.",
"No response or motion",
"Sure… whatever works for you.",
"I just go with it now.",
"I stopped thinking for myself.",
"I wasn’t there. I just complied.",
"Yeah… you’re probably right.",
"It’s fine. Whatever you say.",
"I just want things to be calm.",
"I disappear when it’s tense.",
"I’m just trying to stay close.",
"Are we okay? Are you mad at me?",
"Please don’t leave me alone.",
"I’m whatever you need me to be.",
"Sure, whatever works for you.",
"Okay... I guess I’ll do it.",
"I’m fine. It doesn’t matter.",
"Just tell me what to be.",
"Oh, I don’t mind at all!",
"I just want them to like me.",
"If it helps, I’ll change.",
"Tell me how to be for you.",
"It’s fine — really.",
"Let’s not make this a big deal.",
"I’ll do whatever you need.",
"Just don’t be angry…",
"I just thought I’d help you with that.",
"I hate seeing you like this — let me.",
"I’m fine, don’t worry about me.",
"If I’m not helping, who am I?",
"It’s not a big deal, I’ll manage.",
"I’ll cancel — they need me more.",
"Whatever they want, I’ll become it.",
"If I have to disappear to be loved, so be it.",
"Let’s catch up soon!",
"Do you think they’re mad at me?",
"I hate being alone — it gets too loud inside.",
"Talk to me — anything — I can’t be in my head.",
"I’ve got you.",
"You sounded off — what do you need?",
"You don’t have to do this alone.",
"Let me help — I need to.",
"Let’s catch up soon!",
"We always have this, don’t we?",
"You matter in my day-to-day.",
"Why didn’t you text me back?",
"You’ve got this.",
"Let’s work through it together.",
"I’m here for you, no matter what.",
"Let me take that off your shoulders.",
"Let me keep that off your plate.",
"This is where I draw the line.",
"I can’t let you face that alone.",
"You don’t need to deal with that — I will.",
"I hear you — and here’s what I need.",
"That doesn’t work for me.",
"I won’t be spoken to like that.",
"Enough. I’m done here.",
"Let me know if you'd like a hand.",
"Here’s what we can do next.",
"I need you to focus right now.",
"This stops now — I’ve got it.",
"Would it help if I…?",
"Here’s what might help you here.",
"You need to do this for yourself.",
"This is happening because it has to.",
];
