// === tone.js — T6 Data (Tone Labels) ===

export const tone = [
"Edgy",
"Confrontational",
"Sharp / Aggressive",
"Violent / Feral",
"Cold / Icy",
"Spiteful",
"Harsh / Unyielding",
"Vicious",
"Confident",
"Authoritative",
"Domineering",
"Oppressive / Cold",
"Hesitant",
"Defensive",
"Sharp / Reactive",
"Aggressive",
"Snide / Cool",
"Cold / Precise",
"Sharp / Aggressive",
"Explosive / Harsh",
"Tense / Guarded",
"Slippery / Controlled",
"Strategic / Icy",
"Edgy / Darting",
"Erratic / Buzzy",
"Fractured / Charged",
"Volatile / Loud",
"Unhinged / Overwhelmed",
"Snarky / Wry",
"Icy / Reactive",
"Hot / Spiky",
"Fierce / Raging",
"Quiet / Soft",
"Muted / Flat",
"Cold / Tense",
"Absent / Hollow",
"Light / Evasive",
"Guarded / Tight",
"Flat / Blunt",
"Avoidant / Sharp",
"Slippery / Breezy",
"Controlled / Cool",
"Guarded / Edgy",
"Cloaked / Intense",
"Tense / Hesitant",
"Guarded / Quiet",
"Frantic / Clipped",
"Disoriented / Raw",
"Polite / Guarded",
"Evasive / Soft",
"Jumpy / Disjointed",
"Flat / Faint",
"Flat / Distant",
"Muted / Fuzzy",
"Distressed / Quiet",
"Silent / Absent",
"Low / Muted",
"Numb / Withdrawn",
"Fragile / Quiet",
"Void / Absent",
"Dreamy / Detached",
"Blurry / Numb",
"Hollow / Echoed",
"Disintegrated / Void",
"Stiff / Quiet",
"Flat / Breathless",
"Hushed / Strained",
"Void / Non-Responsive",
"Soft / Automatic",
"Flat / Scripted",
"Hollow / Muted",
"Ghostlike / Passive",
"Gentle / Yielding",
"Soft / Dismissive",
"Smoothing / Careful",
"Faint / Breathless",
"Gentle / Over-eager",
"Over-accommodating",
"Desperate / Tense",
"Dissolved / Fragile",
"Mild / Agreeable",
"Subdued / Guarded",
"Muted / Restrained",
"Hollow / Numb",
"Sweet / Agreeable",
"Careful / Suppressed",
"Pleading / Gentle",
"Over-eager / Fragile",
"Soft / Cooperative",
"Smoothing / Hesitant",
"Worried / Softened",
"Subdued / Fragile",
"Sweet / Helpful",
"Over-involved / Gentle",
"Strained / Dutiful",
"Collapsed / Frantic",
"Submissive / Warm",
"Heavy / Soft-Spoken",
"Fused / Fragile",
"Collapsed / Hollow",
"Friendly / Animated",
"Playful / Slightly Needy",
"Hectic / Scattered",
"Desperate / Overdrive",
"Warm / Soothing",
"Supportive / Focused",
"Protective / Steady",
"Overbearing / Tender",
"Playful / Open",
"Friendly / Grounded",
"Harmonious / Present",
"Needy / Intense",
"Warm / Encouraging",
"Steady / Reassuring",
"Centred / Contained",
"Controlling / Heavy",
"Warm / Cautious",
"Firm / Caring",
"Assertive / Guarded",
"Restrictive / Anxious",
"Steady / Warm",
"Confident / Direct",
"Controlled / Guarded",
"Stern / Final",
"Warm / Motivated",
"Steady / Clear",
"Assertive / Calm",
"Controlled / Firm",
"Respectful / Warm",
"Assured / Calm",
"Firm / Compassionate",
"Clear / Unyielding",
];
